# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclang
    - CONFIG=osx_c_compilertoolchain_c

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "L1jnRMZWFAdEz5YY81kGawoLm4f4Tx7aczteRDiKkqI3Ts4vrdeRxcfUhtBzEkKgSM5Agl0uCC6qUV8vp+kaymTITNMYc1H964jtj9XDU0QvH/4V5Qwa1hcB87cZ9QD1/ek/csQnj8Gs334d92dxOJxWKMGkgQt73RII8fah6tWQHYzlK5Iu3hzzeFh7bJvMi2nTdypCpf0KJmo7VD1Kes1QJpcQOWqFzNpc9m2r5X9LIWCu2KJv03BdASSxG1wLIxYzzvNFJimVvScyqtqUYIoRsjySai4QnhgwY9P4++8+OxBB2HVnU5PUvTMSNAw73qWfmOBf1fdRd6BGlK2PvG84/l5t5WF1tYJfj2iXdvDQs/jWfW1uBXhv/sQZEEVkZc2FiGRPjAtTPrDY/6TUi+fZdLMiUmh/Q0+T7e0D2nF9Jqf3lk5yoj2h9J82k6/EQdwvGn6l6oWEB8DtRO4WRTne44h+YBj3v0wEZLVbbiPJk4MBvd/rMzcPxVBkZwqQLp47W29zxQftoui+0QaGwlMjntaDbXhKTHBoXwFpGZEOThZ9tS+EsEb/BtEzz6lJQc3gbNb2NiG1fDws4s8HRJ2HK6BOLuELmwuKk6lmjc7LCzjoXVTn5ajU1eDi1635qc/bHyQmePF1ti70P7FrNFUEskRkCabS19GQv+j2YDE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
