appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: L1jnRMZWFAdEz5YY81kGawoLm4f4Tx7aczteRDiKkqI3Ts4vrdeRxcfUhtBzEkKgSM5Agl0uCC6qUV8vp+kaymTITNMYc1H964jtj9XDU0QvH/4V5Qwa1hcB87cZ9QD1/ek/csQnj8Gs334d92dxOJxWKMGkgQt73RII8fah6tWQHYzlK5Iu3hzzeFh7bJvMi2nTdypCpf0KJmo7VD1Kes1QJpcQOWqFzNpc9m2r5X9LIWCu2KJv03BdASSxG1wLIxYzzvNFJimVvScyqtqUYIoRsjySai4QnhgwY9P4++8+OxBB2HVnU5PUvTMSNAw73qWfmOBf1fdRd6BGlK2PvG84/l5t5WF1tYJfj2iXdvDQs/jWfW1uBXhv/sQZEEVkZc2FiGRPjAtTPrDY/6TUi+fZdLMiUmh/Q0+T7e0D2nF9Jqf3lk5yoj2h9J82k6/EQdwvGn6l6oWEB8DtRO4WRTne44h+YBj3v0wEZLVbbiPJk4MBvd/rMzcPxVBkZwqQLp47W29zxQftoui+0QaGwlMjntaDbXhKTHBoXwFpGZEOThZ9tS+EsEb/BtEzz6lJQc3gbNb2NiG1fDws4s8HRJ2HK6BOLuELmwuKk6lmjc7LCzjoXVTn5ajU1eDi1635qc/bHyQmePF1ti70P7FrNFUEskRkCabS19GQv+j2YDE=}
