travis:
  secure:
    BINSTAR_TOKEN: mhPePvGvbDFfVrGVQIX87MM1TTT9CoIToQ2iiJ9pKqJVOFWopZNnOCTmjv0eyh2Tij4/cAVfsTMmniHEMWD63kU3ro5m/x94U4wUd7K5Fs3K4uEjdRkln236aymAwiGaFFmPSOug6zGe2W7acPf6NAGpPa94o0e5cyV+0+8HPp6xYDsGl5IJamTNIx9TUgF7WVwkkAagbpVwKcZ48XmFT8dRB16oX6RtvMH1Mlgj+GMrvDUgzpa4yG1zHdaKP48Nf8v71p+GFNOOFmZw2YSFyv/ElAJm8exYvxMQFZJcyjz/AL062xDOPU2Nr0MGXhkRp3SwlYOu8vsZ5xUFvxqI6z25PqUIVUAGiIO+EzOaQu/ETNdfphPGbN0P8WrKKsX39qfrL8yyoyx9DnbjMuMEX76Yjh62Bc8UJz5KJcuGui4cJsgP+WgeDK0yARjUy4OaUodS9hqzOf0wfbHRhIHnqxhxlR1kguRieZCDf0fOo6mvD+UvTfnm5B1Xxz/sZC+TDV/y+oGUvlWa0XIkwhU/rnC4HVIhYTErl1dUgGNKDHnbG8jvLXwYFCcDBgcFrexZqHFqBzOoknT5/SzYv9MDHhMYjBRY+4aGJ3MRySsROroe4uHHi/tevz5XcNk7A17RqVF6JtSFp/QM9XTdLAoGbElA+xyH0wQpVdpzB1VMJl4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
